@hostname=localhost
@port=5172

POST https://{{hostname}}:{{port}}/api/Authentication/Login
Content-Type: application/json
Accept: application/json

###

POST https://{{hostname}}:{{port}}/api/Authentication/Registration
Content-Type: application/json
Accept: application/json

###

PATCH https://{{hostname}}:{{port}}/api/Authentication/Logout
Content-Type: application/json
Accept: application/json

###

PUT https://{{hostname}}:{{port}}/api/Authentication/UpdateToken
Content-Type: application/json
Accept: application/json

###